---
- name: Send notifications to Slack
  uri:
    url: "{{ slack_token }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: 
      text: "The server {{ ansible_hostname }} has restarted"
    body_format: json
    status_code: [200, 204]
  register: result

- name: Send notification to Discord
  uri:
    url: "{{ discord_webhook }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: 
      content: "The server {{ ansible_hostname }} has restarted"
    body_format: json
    status_code: [200, 204]
  register: result