---
- hosts: all
  vars:
    datadog_api_key: "your_datadog_api_key"
    datadog_site: "datadoghq.com"
    datadog_agent_version: "7"
    datadog_config:
      process_config:
        enabled: "true"
      system_probe_config:
        enabled: "true"
  tasks:
    - name: Install kernel headers
      apt:
        name: linux-headers-$(uname -r)
        state: present
      become: true
  roles:
    - role: Datadog.datadog