---
- hosts: node
  vars:
    mqtt_broker_ip: '192.168.0.11'
    mosquitto_retention_period: 1800
    mosquitto_config_file: '/etc/mosquitto/mosquitto.conf'
    channel: '#notification'
    token: 'your-slack-webhook-url'
  tasks:
    - name: Install Mosquitto clients
      become: true
      apt:
        name: mosquitto-clients
        state: present

    - name: Publish message to MQTT topic
      shell: "mosquitto_pub -h '{{ mqtt_broker_ip }}' -t 'test' -m 'Hello from Ansible!'"

    - name: Configure Mosquitto
      copy:
        content: |
          port 1883
          persistence true
          autosave_interval 1800
          persistence_file mosquitto.db
          connection_messages true
          log_timestamp true
          allow_anonymous true
          autosave_on_changes true
          message_size_limit 0
          retained_persistence true
          autosave_interval {{ mosquitto_retention_period }}
        dest: "{{ mosquitto_config_file }}"
      become: true

    - name: Restart Mosquitto
      systemd:
        name: mosquitto
        state: restarted
      become: true
      notify: Mosquitto restarted

    - name: Check Mosquitto status
      service_facts:
      register: service_facts

    - name: Show Mosquitto status
      debug:
        msg: "Mosquitto is running"
      when: "'mosquitto' in service_facts.ansible_facts.services and service_facts.ansible_facts.services['mosquitto'].state == 'running'"

  handlers:
    - name: Mosquitto restarted
      slack:
        token: '{{ token }}'
        msg: 'Mosquitto service has been restarted.'
        channel: '{{ channel }}'
        username: 'Ansible'