---
- hosts: master
  vars:
    mosquitto_config_file: /etc/mosquitto/conf.d/mosquitto.conf
    mosquitto_retention_period: 120
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      become: true

    - name: Install Mosquitto
      apt:
        name: mosquitto
        state: present
      become: true

    - name: Configure Mosquitto
      block:
        - name: Import Mosquitto Configuration
          copy:
            content: |
              port 1883
              persistence true
              autosave_interval 1800
              persistence_file mosquitto.db
              connection_messages true
              log_timestamp true
              allow_anonymous true
              autosave_on_changes true
              message_size_limit 0
              retained_persistence true
              autosave_interval {{ mosquitto_retention_period }}
            dest: "{{ mosquitto_config_file }}"
          become: true

    - name: Restart Mosquitto
      systemd:
            name: mosquitto
            state: restarted
      become: true
    - name: Check Mosquitto status
      service_facts:
      register: service_facts
    
    - name: Show Mosquitto status
      debug:
        msg: "Mosquitto is running"
      when: "'mosquitto' in service_facts.ansible_facts.services and service_facts.ansible_facts.services['mosquitto'].state == 'running'"