---
- hosts: node
  vars:
    mqtt_broker_ip: '192.168.0.11'
  tasks:
    - name: Install Mosquitto clients
      become: true
      apt:
        name: mosquitto-clients
        state: present

    - name: Publish message to MQTT topic
      shell: "mosquitto_pub -h '{{ mqtt_broker_ip }}' -t 'test' -m 'Hello from Ansible!'"