version: '3.8'
services:
  db:
    image: $DB_IMAGE:$DB_TAG
    restart: "${RESTART_POLICY}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MARIADB_AUTO_UPGRADE: "${MARIADB_AUTO_UPGRADE}"
    volumes:
      - "${DB_VOLUME_MOUNT_HOST}:${DB_VOLUME_MOUNT_CONTAINER}"
    env_file:
      - /vagrant_data/.env/.env
  app:
    image: $DOCKER_IMAGE:$DOCKER_TAG
    restart: "${RESTART_POLICY}"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "${DB_MYSQL_HOST}"
      DB_MYSQL_PORT: "${DB_MYSQL_PORT}"
      DB_MYSQL_USER: "${DB_MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      DB_MYSQL_NAME: "${DB_MYSQL_NAME}"
      DISABLE_IPV6: 'true'
    volumes:
      - "${APP_VOLUME_MOUNT_HOST}:${APP_VOLUME_MOUNT_CONTAINER}"
      - "${SSL_VOLUME_MOUNT_HOST}:${SSL_VOLUME_MOUNT_CONTAINER}"
    env_file:
      - /vagrant_data/.env/.env
    depends_on:
      - db

