version: '3.8'
services:
  app:
    image: $DOCKER_IMAGE:$DOCKER_TAG
    restart: $RESTART_POLICY
    ports:
      - $HTTP_PORT:80
      - $HTTPS_PORT:443
      - $ADMIN_PORT:81
    environment:      
      DB_MYSQL_HOST: $DB_MYSQL_HOST
      DB_MYSQL_PORT: $DB_MYSQL_PORT
      DB_MYSQL_USER: $DB_MYSQL_USER
      DB_MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      DB_MYSQL_NAME: $DB_MYSQL_NAME      
      DISABLE_IPV6: 'true'
    volumes:
      - $APP_VOLUME_MOUNT
      - $SSL_VOLUME_MOUNT
    depends_on:
      - db

  db:
    image: $DB_IMAGE:$DB_TAG
    restart: $RESTART_POLICY
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MARIADB_AUTO_UPGRADE: $MARIADB_AUTO_UPGRADE
    volumes:
      - $DB_VOLUME_MOUNT