---
- hosts: all
  become: true
  vars_files:
    - /vagrant_data/.env/.ansible/.env.yml

  handlers:
    - name: Send notification to Slack and Discord
      include_tasks: "{{notifications_server_restart}}"

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Reboot the machine
      reboot:
        msg: "Rebooting for system upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      notify: "Send notification to Slack and Discord"